### ISSUE TITLE
FXDiagram crashes in Eclipse Neon in Ubuntu 14.04

### ISSUE THREAD

**Issue by AjitDingankar** [JanKoehnlein/FXDiagram#51]
I can view FXDiagram of a statemachine example in an EclipseApplication on Windows 10, 
but it crashes on Ubuntu 14.04 (but I can run the standalone Java demo fine). 

The main error shown in the console of the original Eclipse instance is: 
40   [main] ERROR org.eclipse.xtext.service.CompoundModule  - Type org.eclipse.xtext.xbase.file.AbstractFileSystemSupport not present 
However, I'm confused because the log shows libgdk at the top. 

Sorry I'm not familiar with Eclipse packages etc, and I couldn't find any leads from 
web searches for the xtext error, so I decided to file this sighting. I've attached the 
log file and console output. 

Thanks, 
Ajit
==== 

[FXDiagram-Crash-Ubuntu.zip](https://github.com/JanKoehnlein/FXDiagram/files/531491/FXDiagram-Crash-Ubuntu.zip)

**Comment by JanKoehnlein** [comment]
The exception stems from an incompatibility in the domainmodel example from Xtext and should not have an effect on the statemachine example. It should go away once you instantiate the domainmodel example in your workspace (New > Example > Xtext Examples > Xtext Domain-Model Example) and spawn a new runtime workbench (Run > Run config > Eclipse Application).

Anyway, it will not cause your JVM to crash with a coredump. This can only happen when JavaFX or SWT accesses your low-level graphics libraries such as libgtk in a wrong way. Is it a GTK version 3 or 2? Eclipse SWT for GTK 3 is well known for a lot of glitches. Maybe it is related to [this bug](https://bugs.openjdk.java.net/browse/JDK-8160321). There is nothing I can do about this.

**Comment by AjitDingankar** [comment]
Thanks, Jan! I'm on GTK3, so I'll try to downgrade to GTK2 instead of waiting for Java 9. :-)

**Comment by AjitDingankar** [comment]
Just wanted to leave a note on *how* to downgrade to GTK2. 
Simply execute the following in a shell before starting Eclipse: 
export SWT_GTK3=0 
according to 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=430736#c18
