### ISSUE TITLE
Installation of FxDiagram and running the example

### ISSUE THREAD

**Issue by RahulChandrashekar17061984** [JanKoehnlein/FXDiagram#61]
Hi,

Pls share the info of how to deploy FxDiagram into eclipse.

Also kindly share some examples to run the application.

Regds
Rahul.

**Comment by JanKoehnlein** [comment]
I've added the examples to the update-site, so you should now be able to just install FXDiagram and the Eclipse examples directly into your Eclipse. I tested it with a new, bare Eclipse for Eclipse Committers with Java 1.8.0_111 on Mac and it worked out of the box. No more compilation, domainmodel/fowlerdsl plug-in instantiation, start of a new runtime Eclipse necessary, just import the [project with the example models](http://dl.bintray.com/jankoehnlein/FXDiagram/:FXDiagram_Eclipse_Examples.zip) into your workspace as described on the website and have fun.
